### ISSUE TITLE
swarm-listener with docker4aws 18.03-ce does not update on service create / remove

### ISSUE THREAD

**Issue by ambrons** [vfarcic/docker-flow-swarm-listener#63]
**Description**

**Steps to reproduce the issue:**
1. Setup 18.03-ce Docker4AWS Cloudformation
2. Install docker swarm-listener (18.04.05-6)
3. Install swarm stack that includes labels that trigger docker swarm-listener

**Describe the results you received:**
When services are added or removed from swarm-listener there is no update.  The logs act as if it was not notified.

However if you scale swarm-listener to zero and back to 1 again it will read the service labels and update the docker-flow-proxy.  Any updates after this are ignored as before.

**Describe the results you expected:**
Prior to updating our docker4aws cloudformation to use 18.03-ce and re-deploying swarm-listener and docker-flow-proxy things worked as expected.

**Additional information you deem important (e.g. issue happens only occasionally):**
Our stack file for swarm-listener and docker-flow-proxy:
```
version: '3.1'

services:

  proxy:
    image: zcoio/fp-docker-flow-proxy:v1.2.0
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
      - TIMEOUT_SERVER=60
      - CONNECTION_MODE=http-server-close
    secrets:
      - source: cert-esports.pem
        target: cert-esports.pem
        mode: 292
    deploy:
      replicas: 2

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener:18.04.05-6
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

secrets:
  cert-esports.pem:
    external: true

networks:
  proxy:
    external: true
```
We're using a custom version of docker-flow-proxy to including our own error templates.  Our custom image uses `FROM vfarcic/docker-flow-proxy:18.04.06-12`.  However the issue is with swarm-listener as it doesn't even get updates or try to update docker-flow-proxy when a service is updated.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
